---
title: Jekyll PWA Starter
timezone: UTC
destination: _site/
domainname: https://pwa-jekyll-starter.netlify.com
baseurl: /
sitename: My Website
assetsurl: /static-assets/
markdown: kramdown
highlighter: rouge
exclude:
- config
- screenshots
- node_modules
- gulpfile.js
- package.json
- src
- README.md
- Gemfile
- Gemfile.lock
- Dockerfile
- docker-entrypoint.sh
port: 4000
plugins:
  - liquid-md5
sass:
  style: :compressed
# webmentions = true/false
# bootstrap = true/false
webmentions: true
bootstrap: false

