backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

media_folder: "/static-assets/images/" # Media files will be stored in the repo under images/uploads
public_folder: "/static-assets/images/uploads" # The src attribute for uploaded media will begin with /images/uploads

collections: # A list of collections the CMS should be able to edit
  - name: "posts" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Post" # Used in the UI, ie.: "New Post"
    description: >
      Traditional blog posts.
    folder: "_posts"
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}/"
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {label: "Title", name: "title", widget: "string", tagname: "h1"}
      - {label: "Publish Date", name: "date", widget: "datetime", format: "YYYY-MM-DD hh:mma"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Layout", name: "layout", widget: "hidden", default: "posts"}
      - {label: "Categories", name: "categories", widget: "string", default: "blog"}
      - {label: "Abstract", name: "abstract", widget: "markdown"}
      - {label: "Author", name: "author", widget: "text"}
      - {label: "permalink", name: "permalink", widget: "text", default: "/posts/:categories/:title/"}
    meta:
      - {label: "SEO Description", name: "description", widget: "text"}
  - name: "notes" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Notes" # Used in the UI, ie.: "New Post"
    description: >
      Short notes.
    folder: "_posts/notes"
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}/"
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {label: "Title", name: "title", widget: "string", tagname: "h1"}
      - {label: "Publish Date", name: "date", widget: "datetime", format: "YYYY-MM-DD hh:mma"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Layout", name: "layout", widget: "hidden", default: "posts"}
      - {label: "Categories", name: "categories", widget: "string", default: "note"}
      - {label: "Abstract", name: "abstract", widget: "markdown"}
      - {label: "Author", name: "author", widget: "text"}
      - {label: "permalink", name: "permalink", widget: "text", default: "/posts/:categories/:title/"}
    meta:
      - {label: "SEO Description", name: "description", widget: "text"}
  - name: "links" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Links" # Used in the UI, ie.: "New Post"
    description: >
      Links
    folder: "_posts/links"
    slug: "{{year}}-{{month}}-{{day}}-{{title}}/"
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {label: "Title", name: "title", widget: "string", tagname: "h1"}
      - {label: "Publish Date", name: "date", widget: "datetime", format: "YYYY-MM-DD hh:mma"}
      - {label: "Link", name: "link", widget: "string"}      
      - {label: "Abstract", name: "abstract", widget: "markdown"}
      - {label: "Body", name: "body", widget: "text"}
      - {label: "Layout", name: "layout", widget: "hidden", default: "links"}
      - {label: "Categories", name: "categories", widget: "string", default: "link"}
      - {label: "permalink", name: "permalink", widget: "text", default: "/posts/:categories/:title/"}
    meta:
      - {label: "SEO Description", name: "description", widget: "text"}
      
